# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false
  bridges:
    br0:
      interfaces: [eno1]
      addresses: [192.168.20.250/24]
      gateway4: 192.168.20.1
      nameservers:
        addresses: [192.168.20.1]
        search: [lunix.lan]
  version: 2

